config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/' => 'static_pages#home'

  get '/about' => 'static_pages#about'

  get '/portfolio' => 'static_pages#portfolio'

  get '/blog' => 'static_pages#blog'

  get '/contact' => 'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def portfolio
  end

  def blog
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AboutMeSite</title>
  <link href='http://fonts.googleapis.com/css?family=Lobster|Oswald' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Montserrat', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav>
      <ul>
        <li><%= link_to('Home', root_path) %></li>
        <li><%= link_to('About', about_path) %></li>
        <li><%= link_to('Portfolio', portfolio_path) %></li>
        <li><%= link_to('Blog', blog_path) %></li>
        <li><%= link_to('Contact Me', contact_path) %></li>
      </ul>
    </nav>
  </header>
  <div class="<%= params[:action] %>-wrapper">
    <%= yield %>
  </div>  
  <footer>
    <li>Contact</li>
    <li>LinkedIn</li>
    <li>Github</li>
  </footer>

</body>
</html>

app/views/static_pages/about.html.erb
<p class="about-p">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p class="about-p">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<%= link_to('See my Portfolio', portfolio_path, class: 'about-link') %>

app/views/static_pages/blog.html.erb
<h1>This is my blog</h1>

app/views/static_pages/home.html.erb
<div class="home-welcome">
  <p id="home-name">Erika Jonikaite</p>
  <p id="home-subtitle">Web Developer</p>
</div>

<div class="skills">
  
</div>

<div class="quotation">
  
</div>

app/views/static_pages/portfolio.html.erb
<%= image_tag('300.gif', class: 'portfolio-img') %>
<%= image_tag('300.gif', class: 'portfolio-img') %>
<%= image_tag('300.gif', class: 'portfolio-img') %>
<%= image_tag('300.gif', class: 'portfolio-img') %>
<%= image_tag('300.gif', class: 'portfolio-img') %>
<%= image_tag('300.gif', class: 'portfolio-img') %>